= Видение


Краткое наименование: Мониторинг фистулы.

Полное наименование: Информационная система мониторинга фистулы у пациентов, которым требуетсяя гемодиализ.


== Введение

На входе системы поступает звук фистулы, который записывается,
анализируется и выдает результат состояния фистулы в реальном
времени на телефон пациента.

== Функциональные возможности

  •	Система должна иметь функцию регистрации пациента
  •	Система должна иметь функцию изменения данных пациента
  •	Система должна хранить все аудиозаписи пациентов на сервере в файловой системе
  •	Система должна иметь функцию учета активного и пассивного оборудования
  •	Система должна иметь функцию авторизации, аутентификации и идентификации.
  •	Система должна иметь функцию отправки Push-уведомления пациенту о посещении врача или процедуры.
  •	Системы должна иметь функцию отправки Push-уведомления доверительному лицу, об изменении состояния фистулы
  •	Система должна иметь функцию регистрации пациентов на прием к врачу через мобильное приложение
  •	Система должна функцию связи между пациентом и врачом в виде чата
  •	В мобильном приложении должна быть реализована вкладка, посвящённая инструкции использования мобильного приложения и устройства “Киприот”.
  •	Система должна иметь функцию скачивания обновления для мобильного приложения при подключении его к сети.
  •	Мобильное приложение должно иметь  функцию создания расписания пациента на гемодиализ
  •	Мобильное приложение должно иметь функцию уведомления об процедуре гемодиализа за 30 минут до его начала
  •	Система должна иметь функцию авторизации, аутентификации и идентификации.
  •	В мобильном приложении должна быть реализована вкладка, посвящённая инструкции использования мобильного приложения и устройства “Киприот”.
  •	Система должна иметь функцию скачивания обновления для мобильного приложения при подключении его к сети.
  •	Раз в минуту устройство должно записывать аудиофайл состояния фистулы	в течении 10 секунд
  •	Система должна хранить аудиофайлы на устройстве “Киприот”
  •	Система должна передавать новые аудиозаписи на сервер при выходи устройства в сеть
  •	Система должна иметь функции освобождения памяти устройство от старых аудиозаписей
  •	Система должна иметь функцию скачивания обновления устройства “Киприот” при подключении его к сети
  •	Система должна иметь функцию отправки Push-уведомление пациенту о состоянии памяти устройства и требования подключение его к сети
  •	Система должна иметь функцию отправки Push-уведомление пациенту о состоянии заряда устройства и требования подключение его к электросети для подзарядки.
  •	Система должна иметь функцию журнала регистрации изменений 	состояния пациента
  •	Система должна иметь функцию экспорта значений частот аудиозаписи в формата	csv.
  •	Система должна иметь функцию создания графиков и спектрограмм по файлам csv

== Рынок

=== SWOOT-анализ

. Внутренние сильные стороны

.. Много желания
.. Интересная тематика
.. Опыт работы с медицинским оборудованием
.. Знакомства с пациентами

. Внутренние слабые стороны

.. Мало опыта в разработки мобильных приложения
.. Трудная предметная область
.. Параллельное изучение предметной области и реализация проекта

. Внешние возможности

.. Защита диплома для получение бакалаворской степени
.. Государственная поддержка
.. Интерес со стороны гемодиалезных центров
.. Малое количество прямых конкурентов

. Внешние угрозы

.. Пациентом не понравится устройство или неумеет пользоваться телефоном
.. Возможное отсутствие инвестора
.. Возможное отсутствие гранта

== Заинтересованные лица


. Заинтересованные лица
|===
|Заинтересованное лицо |Интерес заинтересованного лица  |Задачи | Текущее решение
|Руководитель практики |Создать хороший стартап|Ленивый студент|Но он не безнадежен
|Студент |Допуститься до защиты диплома |Разобратся в предметной области и написать диплом|Разбираю
|Врач|Получить гранд на развитие стартапа |Помочь студенту в предметной область|Устроить встречу студенту с пациентами для наглядного изучения
|Пациенты |Прожить дольше |Заставить пациентов носить устройство|Надеюсь врач уговорит их :3
|Больница |||Cell in column 2, row 2

|===

== Конкуренты

|===
|Конкуренты|Отличительные признаки
|Фитнес браслеты и фитнес часы| Свобода на руке, прослушивание фистулы
|Диктофон| Прослушивание фистулы, анализ звука, взаимодействие с телефоном
|===


== Дополнительные спецификации


=== Нефунциональные требования

. Мобильное приложение для android и ios
. Понятный интерфейс и функционал
. Наличие инструкции

=== Правила

== Словарь терминов

|===
|Термин|Описание | Синонимы
|Фистула| Хирургическое соединение вены и артерии |Вена, артерия, fistula
|Гемодиализ| Процедура очистки крови вне организма с использованием
            искусственного фильтра (диализатора), через который проходит
            кровь пациента и освобождается от шлаков и избытка жидкости.|
|Перитонеальный диализ|Это способ очистки крови внутри
                       организма|
|===
